### ISSUE TITLE
Bash and Zsh command autocompletion

### ISSUE THREAD

**Issue by jozuas** [nimbo-sh/nimbo#13]
To make the experience of using Nimbo more seamless, we should support Bash and Zsh autocompletion.

**Comment by noreferences** [comment]
Click can automatically generate Bash/Zsh/Fish autocompletion files https://click.palletsprojects.com/en/8.0.x/shell-completion/. Once Nimbo is packaged for Brew and apt, we should add general instructions on how to enable autocompletion if not installed from brew, apt or nix.

**Comment by noreferences** [comment]
Related - https://github.com/nimbo-sh/nimbo/issues/14
