### ISSUE TITLE
nimbo unable to read pem key 'load pubkey "mykey.pem": invalid format'

### ISSUE THREAD

**Issue by SebastianCallh** [nimbo-sh/nimbo#19]
Reproduced by 
1. Generate a key `mykey.pem` in the AWS console and download it
2. Copy `mykey.pem` to project dir
3. Put `instance_key: mykey.pem` in `nimbo-config.yml`
4. Run `nimbo test-access`
5. Get a bunch of `load pubkey "mykey.pem": invalid format` errors

Inspecting the key shows it looks fine with correct header/footer and can be used to manually SSH onto EC2 instances.  Is there something Nimbo does differently when it comes to keys?

**Comment by seuqaj114** [comment]
Hey Sebastian,

Have you ran `chmod 400 mykey.pem` ?

**Comment by noreferences** [comment]
Hey Sebastian,

Could you please share the exact error messages that you are getting? It is very hard for us to deduce what is happening without this information.

I generated a key with name `mykey.pem` and used it without any issues.

**Comment by SebastianCallh** [comment]
Thank you for your responses! 
@seuqaj114 Forgot to mention that step. Yes I did chmod the key. @noreferences the error message is printed exactly as typed in step 5 unfortunately. Is there some verbose mode I am not seeing? The config file is the one generated from the template with some updated values described below

```
# Data paths
local_results_path: data/results  # relative to project root
local_datasets_path: data/datasets  # relative to project root
s3_results_path: s3://resultpath
s3_datasets_path: s3://datasetpath

# Device, environment and regions
aws_profile: myprofile
region_name: eu-west-1
instance_type: p2.xlarge
spot: yes

image: ubuntu18-latest-drivers
disk_size: 128
conda_env: env.yml

# Job options
run_in_background: yes
persist: no

# Permissions and credentials
security_group: default
instance_key: mykey.pem
role: NimboFullS3AccessRole`
```

**Comment by noreferences** [comment]
This looks bizarre - have you tried generating a new key from the AWS EC2 console? I've looked around what could be a cause and I just don't see what could be causing this (given the fact that `mykey.pem` works when you normally SSH to instances). The only way I was able to reproduce your issue was to mess up the key by removing the header row. But at that point the error message makes sense.

**Comment by SebastianCallh** [comment]
Yeah I can't make sense of it either. Looking closer at the logs for when i manually SSH I actually _do_ find the same error (it was buried under ssh status messages and the instance welcome message so I didn't catch it before) , but the SSH session still opens and everything works. So maybe `awscli` is performing some recovery magic. 

I still have no clue what's up but it looks like the problem lies in my setup. Thank you for your help, and best of luck with `nimbo`! I look forward to trying it out myself

**Comment by SebastianCallh** [comment]
Solved by creating a key manually with `ssh-keygen` and importing it with the **same name** as the file in AWS (for `mykey.pub` import it as `mykey`), and then pointing the `instance_key` in `nimbo-config.yml` to the key. I have no clue why the key generated by AWS does not work with _their own_ services, but the problem is definitely not related to `nimbo`.
