### ISSUE TITLE
issue creating spot instances

### ISSUE THREAD

**Issue by raijinspecial** [nimbo-sh/nimbo#20]
Hi! Thanks for this nice tool.

I'm having an issue with bringing up spot instances. 

In nimbo-config.yml if spot is set to no, it works as expected, but setting to yes gives me this error:
```
Exception: {'Code': 'bad-parameters', 'Message': 'Your Spot request failed due to bad parameters. 
Spot request cannot be fulfilled due to invalid availability zone.', 
'UpdateTime': datetime.datetime(2021, 5, 12, 19, 8, 50, tzinfo=tzutc())}
```

I have tried on both ubuntu 20.04 and macos and meet the same error. On my linux box I tried both installing nimbo with pip and from source and met this availability zone error, on macos I've only tried installing nimbo with pip.

Is this a known issue? How can it be resolved?

Thanks

**Comment by noreferences** [comment]
Hi, could you please share your Nimbo configuration file? I suspect this has to do with region and instance type configuration.

**Comment by raijinspecial** [comment]
Sure, I was not able to find where the availability zone is specified.

```
# nimbo-config.yml

local_datasets_path: data  # relative to project root
local_results_path: results    # relative to project root
s3_datasets_path: s3://...
s3_results_path: s3://...

# Device, environment and regions
aws_profile: default
region_name: us-east-1
instance_type: p3.8xlarge
spot: yes

image: ubuntu18-latest-drivers
disk_size: 1024  # In GB
conda_env: nimbus.yml  # denotes project root

# Job options
run_in_background: no
persist: no  # whether instance persists when the job finishes or on error

# Permissions and credentials
security_group: default
instance_key: iron_key2.pem  # can be an absolute path
role: NimboFullS3AccessRole
```

**Comment by seuqaj114** [comment]
Could you try a different instance_type (still with spot: yes) and a different region? Just to check.

I don't think this is an issue with Nimbo, so the OS you're launching it from or the installation method shouldn't matter.

**Comment by seuqaj114** [comment]
Additionally, could you try to create that same spot instance (p3.8xlarge in us-east-1) via de AWS console?

**Comment by raijinspecial** [comment]
So I have tried g4dn.4-8-12-metal, p3.16, p3dn24 and p4d via nimbo all of which give me the same error. I have not tried using the aws console to create a spot instance yet, I usually use spotty for that and preemptions notwithstanding I am able to bring spots up like that.

I will try in the console and let you know.

Thanks for taking the time to help me with this.

**Comment by noreferences** [comment]
Just not I tried to request a sport for `t3.medium` and I did not encounter the issue the reported issue. I'll try your instance type.

**Comment by noreferences** [comment]
@raijinspecial I just ran Nimbo succsefully with the following config file
```
local_datasets_path: in
local_results_path: out/
s3_datasets_path: s3://nimbo-juozas/nimbo-test/in/
s3_results_path: s3://nimbo-juozas/nimbo-test/out

aws_profile: default
region_name: us-east-1
instance_type: p3.8xlarge
spot: yes

image: ubuntu18-latest-drivers
disk_size: 128
conda_env: environment.yml

# Job options
run_in_background: yes
persist: no

security_group: default
instance_key: us-east-1-juozas.pem
role: NimboFullS3AccessRole
```

**Comment by noreferences** [comment]
@raijinspecial sorry about the delay, still waiting for AWS to allow us to run `p3` family instances.

**Comment by raijinspecial** [comment]
No worries at all. 

I get the same problem with t.3, p2, c5, and inf1 as well, I can still launch all of them no problem if its not spot.

**Comment by noreferences** [comment]
Alright, in that case can't replicate :(

**Comment by seuqaj114** [comment]
@raijinspecial Did you manage to launch the spot instances?

**Comment by noreferences** [comment]
Reopen if there are more details
