### ISSUE TITLE
AWS Credential errors

### ISSUE THREAD

**Issue by Ouwen** [nimbo-sh/nimbo#33]
Really like the concept of nimbo, it is quite lightweight for launching instances. However, I have not been able to give it a try due to AWS key errors. Would love to chat more about using this tool though.

**Comment by noreferences** [comment]
If you could provide more context, I'd be more than happy to help.

**Comment by noreferences** [comment]
>AWS key errors

Nimbo should provide actionable messages if something is wrong with your instance key.

If you are encountering `load pubkey "mykey.pem": invalid format`, then regenerate the key. Another person encountered this in issue https://github.com/nimbo-sh/nimbo/issues/19

**Comment by Ouwen** [comment]
The `test-access` gave some more cli visibility.

```
You have the necessary S3 read/write permissions from your computer ✓
Launching test instance... 
An error occurred (AuthFailure) when calling the DescribeSecurityGroups 
operation: AWS was not able to validate the provided access credentials
```

The credentials are successfully set by `nimbo admin-setup <my-admin-profile> --full-s3-access`
but it seems there are still some hidden issues.

**Comment by noreferences** [comment]
@Ouwen can you share your `nimbo-config.yml` file?

I've been able to pinpoint the [issue](https://aws.amazon.com/premiumsupport/knowledge-center/iam-validate-access-credentials/), but would benefit from knowing which region you're on so that I could replicate the issue and then test the fix.

P.S. next time you should use the bug template for reporting bugs.

**Comment by Ouwen** [comment]
Hey @noreferences sorry about that I didn't see that you guys had a bug template up.

```
# Data paths
local_datasets_path: test_datasets  # relative to project root
local_results_path: test_results    # relative to project root
s3_datasets_path: s3://gradient-nimbo
s3_results_path: s3://gradient-nimbo

# Device, environment and regions
aws_profile: default
region_name: us-east-1
instance_type: p2.xlarge
spot: no

image: ubuntu18-latest-drivers
disk_size: 128  # In GB
conda_env: your-env-file.yml  # denotes project root

# Job options
run_in_background: no
persist: no  # whether instance persists when the job finishes or on error

# Permissions and credentials
security_group: default
instance_key: nimbo.pem  # can be an absolute path
role: NimboFullS3AccessRole
```

Looks like i'm able to run `nimbo test-access` with successful checks. Would still love to chat if you have the time.

**Comment by noreferences** [comment]
@Ouwen what did you change to fix your issue?

> Would still love to chat if you have the time.

Email norkus@nimbo.sh and we can set something up.
