### ISSUE TITLE
Changing nimbo-config.yml name

### ISSUE THREAD

**Issue by JoshuaNg123** [nimbo-sh/nimbo#34]
Hello,

We have a docker container which runs as a microservice that uses nimbo for training a model on EC2. However, if two users in the same container were to run a job at the same time than someone may use the other person's nimbo-config.yml file. 

Is there a way to change the nimbo-config.yml name so that each user can have their own nimbo configuration file.

**Comment by noreferences** [comment]
There is not at the moment, but should not be difficult to add.

**Comment by JoshuaNg123** [comment]
Is there any update?

**Comment by noreferences** [comment]
Terribly sorry about the delay, some urgent stuff came up. I'll look into it this week.

**Comment by noreferences** [comment]
@JoshuaNg123 is an environment variable sufficient for setting config file? Right now I have a half-baked implementation of setting from command line option and I really don't like what it has done to the codebase.

**Comment by JoshuaNg123** [comment]
I believe an environment variable could work

**Comment by noreferences** [comment]
@JoshuaNg123 after @seuqaj114 reviews my changes, the release will be made shortly.

**Comment by noreferences** [comment]
Done and released
