### ISSUE TITLE
Docker support (as alternative to conda)

### ISSUE THREAD

**Issue by hellno** [nimbo-sh/nimbo#39]
**Is your feature request related to a problem? Please describe.**
Conda env setup takes >45 mins every time I'm starting a new instance. This gets 10x more annoying when relying on spot instances. 

**Describe the solution you'd like**
Instead of creating the same conda environment on each new instance, why not have a docker image that can be ready to start much quicker

**Additional context**
Would love any pointers how to add this to nimbo. I'd be up for creating a PR depending on the capacity needed.
Is this on the feature roadmap for nimbo anyway? (Is there a feature roadmap? :) )

Thanks, would love to hear your thoughts on this

**Comment by noreferences** [comment]
You can create an AWS AMI and set it from your Nimbo config to achieve exactly the same effect.

![image](https://user-images.githubusercontent.com/13085275/141989520-4b1026c2-ba28-4a02-b419-21ec73dd472d.png)

**Comment by noreferences** [comment]
You can also see how the images are created in https://github.com/nimbo-sh/nimbo/tree/master/src/nimbo/ami to spin off your own.

**Comment by hellno** [comment]
Sweet, custom AMI seems like a great solution, thanks!

Two related comments:
when using `image: ubuntu18-cuda11.0-cudnn8.0-conda4.9.2` in `nimbo-config.yml`
I get the error: 
`The image ubuntu18-cuda11.0-cudnn8.0-conda4.9.2 was not found in the image catalog managed by Nimbo.
Check https://docs.nimbo.sh/managed-images for the list of managed images.
`

When using `image: ami-0189241054cf4869f`  in `nimbo-config.yml`
I get the error: 
`An error occurred (AuthFailure) when calling the RunInstances operation: Not authorized for images: [ami-0189241054cf4869f]
`

Is only `ubuntu18-latest-drivers` supported from the catalog?

**Comment by noreferences** [comment]
In regards to the first question - I'll have to check when I come home
later today.

In regards to second - are you able to launch the AMI from your AWS console
as the user defined in nimbo config? The error suggests that there has to
be some issues with AWS permissions.

A quarta, 17/11/2021, 17:53, hellno ***@***.***> escreveu:

**Comment by noreferences** [comment]
> when using image: ubuntu18-cuda11.0-cudnn8.0-conda4.9.2 in nimbo-config.yml
I get the error:
The image ubuntu18-cuda11.0-cudnn8.0-conda4.9.2 was not found in the image catalog managed by Nimbo. Check https://docs.nimbo.sh/managed-images for the list of managed images.

It seems that the region that you are trying to use this image from is not a region where we are providing the AMIs. We are intending to move away from Nimbo managed images, so it's better to create your own.
