### ISSUE TITLE
Allow passing config parameters as environment variables

### ISSUE THREAD

**Issue by andrenmelo** [nimbo-sh/nimbo#5]
It would be useful to be able to pass certain parameters as environment variables. For example, suppose I want to commit a config file, but each user of the repo has a different key. With the current setup this wouldn't work, because everyone has different entries for this field:

`instance_key: /home/andre/andre-key.pem`

A similar issue would arise when running a CI job, for example.

One possible solution is to be able to pass this parameter (and perhaps others) as an environment variable. So something like this:

`instance_key: $NIMBO_KEY`

Cheers and keep up the great work.

**Comment by noreferences** [comment]
Good idea, we'll work on it. Thanks :)

**Comment by alex-eyre** [comment]
Attempted in #9

**Comment by noreferences** [comment]
PR merged to master, will be released soon.
